### ISSUE TITLE
Support arm64 architecture

### ISSUE THREAD

**Issue by malshan1993** [Ripwords/starnetGUI#1]
Can make it for arm64  architecture?

**Comment by Ripwords** [comment]
The framework i used to build this GUI is based on the [Tauri](https://tauri.studio/) project. I have asked the devs from Tauri, and their reply was "Generally it should work". So i don't see why StarnetGUI wouldn't work with an arm64 architecture.

However, my application is only the user interface, not starnet++ itself, and from what i know, there are already many people asking the author of starnet++ to release an arm64 version. 

There isn't much i can do for starnet++ you'll just have to wait for the author. But if you are referring to an issue with the user interface, feel free to provide more details here
