### ISSUE TITLE
File name of Output File

### ISSUE THREAD

**Issue by RalfRalf1** [Ripwords/starnetGUI#4]
Hi Ripwords, 

first of all thanks a lot for this great tool you provide to use for free. It really makes life much easier with Starnet++.
I have no bug, but a recommendation for a next version to implement:
Could you may change the output filename creation in a way, that the input filename is used, but extended with _starless for example?
E.g. if the input filename is NGC7000.tif, then the output filename is NGC7000_starless.tif.
This would make it much easier to identify the output files compared to starless1, starless2, starless3 filenames, in case of more files in a batch. 

Thanks a lot
Ralf

**Comment by Ripwords** [comment]
ahh that's a good idea, I'll get to it after my exams are done. Thanks for the recommendation!

**Comment by RalfRalf1** [comment]
Great, thanks a lot for your fast and positive response. Looking forward to it. 
Good luck for your exams.

**Comment by Ripwords** [comment]
![image](https://user-images.githubusercontent.com/58784686/190450497-bc6f44b4-f82e-44f0-954b-5f1948df27d8.png)
I think i have it working now, will be available for update soon

UPDATE:
The update is available now :)

**Comment by RalfRalf1** [comment]
Wow that was really fast! Just updated and checked the new feature. It works perfect. Great work, well done. 
Thanks a lot for the tool.
Hope you exams worked fine?

**Comment by Ripwords** [comment]
It's actually next week, but i looked at the code and it didn't seem too hard to do it, so i updated it first 🤣
