### ISSUE TITLE
Starnet Timeout 

### ISSUE THREAD

**Issue by TheLowerBeat** [Ripwords/starnetGUI#5]
I've tried multiple times without success. I'm not entirely sure if in "starnet directory" I have to put the directory where this gui is installed or if I have to put the directory in which the program is installed. Either way it doesn't work, it says "starnet timed out". I checked and StarnetV2 can process my images so that's not the problem. I do have the .exe file of starnetV2 on an different disk from your gui, could that be the problem? I need this gui because I have a couple hundreds images from which to remove stars and I need to be able to do it in batch mode

**Comment by Ripwords** [comment]
So the directory refers to the folder, in which the starnet .exe file is located at. For example if you have a folder named abc in which the .exe file for starnet is inside, using the gui you would select that folder. I will create another short YouTube video to demonstrate this soon.

**Comment by Ripwords** [comment]
Note that the GUI Setting selects the file path with the starnet.exe folder
Do let me know if they are still any other issue
FileExplorer File Path
![image](https://user-images.githubusercontent.com/58784686/215955480-008e74ae-e4dc-4d81-bcba-5b4e1e1c23d3.png)

GUI Setting
![image](https://user-images.githubusercontent.com/58784686/215955590-fd483b7e-42e1-4021-99a3-21c7f3dd3837.png)

**Comment by TheLowerBeat** [comment]
I've tried to reinstall everything and chose my directories carefully but still get the same problem.
The GUI iteslf is installed in C:\Program Files\starnetGUI. I attatched some screenshots showing that before timing out it does create the temporary tiff files but then everything stops.
 

![image](https://user-images.githubusercontent.com/90135272/216066144-3a5ee84b-3e87-4d3f-a814-694786fe271f.png)

![image](https://user-images.githubusercontent.com/90135272/216066160-7ef700fa-6df7-484f-a4cc-7c1f7812677d.png)

![image](https://user-images.githubusercontent.com/90135272/216067148-5399670e-fedc-4c2b-b16d-be630058a29c.png)

**Comment by Ripwords** [comment]
If starnet works for you usually without the gui, may I know if it usually takes a long time to start? If your pc specs take more than 10 seconds for starnet to run the timeout will be triggered. 

That is why I created a setting for people to increase the timeout period. If it is the case that it usually takes awhile for it to start for you, you can try increasing it to larger number and see if anything happens. Meanwhile I will try to identify if they are other possibilities that is creating this issue

**Comment by Ripwords** [comment]
I think I've noticed your issue. The starnet that you need to download is the command line tool version https://starnetastro.com/wp-content/uploads/2022/03/StarNetv2CLI_Win.zip

The starnet program that you've installed is the starnetGUI that the author of starnet has created which has a simpler interface. 

To be able to use the GUI that I've made you need the command line version which I have linked above. Hopefully this will solve your issue.

**Comment by TheLowerBeat** [comment]
That did solve my problem! Thank you so much! I might actually be able to process C/2022 the way I visioned it.
